#!/usr/bin/env python3
# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Canonical source/dependency bundles. Only explicit updates resolve dependencies."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys

import assembly_dependencies as dependencies
import assembly_sources as sources
import build_provenance
import image_inputs

ROOT_MODULE = "github.com/kubernetes-csi/csi-sidecars"
LIB_MODULE = "github.com/kubernetes-csi/csi-lib-utils"
LIB = str(dependencies.LIBRARY)
LOCK = "tools/assembly/dependencies.lock.json"
CANDIDATE = "tmp/dependencies.candidate.json"
MANIFESTS = ("go.mod", "go.sum", "go.work", "go.work.sum", f"{LIB}/go.mod", f"{LIB}/go.sum")
FIELDS = {"schema_version", "sources", "inputs_sha256", "go_version", "manifests", "modules",
          "vendor_sha256", "adapted_vendor_sha256", "payload_sha256"}
DIGEST = re.compile(r"[0-9a-f]{64}")
SEMVER = re.compile(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
                    r"(?:-([0-9A-Za-z.-]+))?(?:\+incompatible)?")


def encoded(value):
    return (json.dumps(value, sort_keys=True, indent=2) + "\n").encode()


def sha(data):
    return hashlib.sha256(data).hexdigest()


def safe_path(root, name):
    path = root / name
    for parent in (path, *path.parents):
        if parent == root:
            break
        if parent.is_symlink():
            raise ValueError(f"symlink is not a canonical input: {name}")
    return path


def tree_hash(root, paths):
    inventory = {}
    for path in sorted(paths):
        name = path.relative_to(root).as_posix()
        safe_path(root, name)
        if not path.is_file():
            raise ValueError(f"not a regular input file: {name}")
        inventory[name] = [bool(path.stat().st_mode & 0o111), sha(path.read_bytes())]
    if not inventory:
        raise ValueError("empty dependency/input inventory")
    return sha(encoded(inventory))


def inputs_hash(root):
    # The provenance lock binds the entire checked release-tools inventory,
    # including local modifications, modes, and link targets. Root build files
    # are maintained inputs too, never regenerated by sync.
    build_provenance.verify(root)
    image_inputs.load(root)
    paths = [safe_path(root, name) for name in (
        "tools/assembly/build-environment.lock.json", build_provenance.LOCK, image_inputs.LOCK,
        *build_provenance.ROOT_FILES)]
    for path in (root / "tools").rglob("*"):
        if path.is_symlink():
            raise ValueError(f"symlink in maintained inputs: {path.relative_to(root)}")
        if path.suffix in (".go", ".py", ".sh"):
            paths.append(path)
    return tree_hash(root, paths)


def vendor_hash(root):
    vendor = safe_path(root, "vendor")
    paths = [p for p in vendor.rglob("*") if not p.is_dir() or p.is_symlink()]
    if not (vendor / "modules.txt").is_file():
        raise ValueError("missing vendor/modules.txt")
    return tree_hash(vendor, paths)


def manifests(root):
    result = {}
    for name in MANIFESTS:
        path = safe_path(root, name)
        content = path.read_bytes().decode("utf-8") if path.exists() else None
        if content is None and name != "go.work.sum":
            raise ValueError(f"missing canonical manifest: {name}")
        result[name] = {"content": content, "sha256": sha(content.encode()) if content is not None else None}
    return result


def normalize_modules(modules):
    result = []
    seen = set()
    for module in modules:
        if not isinstance(module, dict) or not isinstance(module.get("Path"), str):
            raise ValueError("invalid module graph entry")
        path = module["Path"]
        if path in seen:
            raise ValueError(f"duplicate module: {path}")
        seen.add(path)
        entry = {"Path": path}
        if module.get("Main"):
            if path not in (ROOT_MODULE, LIB_MODULE):
                raise ValueError(f"unexpected workspace module: {path}")
            entry["Main"] = True
        else:
            version = module.get("Version")
            if not isinstance(version, str):
                raise ValueError(f"missing module version: {path}")
            version_key(version)
            entry["Version"] = version
        if "Replace" in module:
            replacement = module["Replace"]
            if not isinstance(replacement, dict) or not replacement.get("Version"):
                raise ValueError(f"unlocked local replacement: {path}")
            if not isinstance(replacement.get("Path"), str) or not isinstance(replacement["Version"], str):
                raise ValueError(f"invalid replacement: {path}")
            version_key(replacement["Version"])
            entry["Replace"] = {key: replacement[key] for key in ("Path", "Version")}
        result.append(entry)
    if not result:
        raise ValueError("empty module graph")
    return sorted(result, key=lambda item: item["Path"])


def validate(bundle):
    if not isinstance(bundle, dict) or set(bundle) != FIELDS:
        raise ValueError("invalid dependency bundle fields")
    if type(bundle["schema_version"]) is not int or bundle["schema_version"] != 1:
        raise ValueError("unsupported dependency bundle schema")
    sources.validate(bundle["sources"])
    for key in ("inputs_sha256", "vendor_sha256", "adapted_vendor_sha256", "payload_sha256"):
        if not isinstance(bundle[key], str) or not DIGEST.fullmatch(bundle[key]):
            raise ValueError(f"invalid {key}")
    if not isinstance(bundle["go_version"], str) or not re.fullmatch(r"go1\.[0-9]+\.[0-9]+", bundle["go_version"]):
        raise ValueError("expected an exact Go patch version")
    if not isinstance(bundle["manifests"], dict) or set(bundle["manifests"]) != set(MANIFESTS):
        raise ValueError("invalid canonical manifest inventory")
    for name, entry in bundle["manifests"].items():
        if not isinstance(entry, dict) or set(entry) != {"content", "sha256"}:
            raise ValueError(f"invalid manifest: {name}")
        content = entry["content"]
        if content is None and name == "go.work.sum" and entry["sha256"] is None:
            continue
        if not isinstance(content, str) or sha(content.encode()) != entry["sha256"]:
            raise ValueError(f"manifest checksum mismatch: {name}")
    if (not isinstance(bundle["modules"], list) or
            encoded(normalize_modules(bundle["modules"])) != encoded(bundle["modules"])):
        raise ValueError("noncanonical module graph")
    payload = {key: value for key, value in bundle.items() if key != "payload_sha256"}
    if sha(encoded(payload)) != bundle["payload_sha256"]:
        raise ValueError("dependency bundle payload checksum mismatch")
    return bundle


def load(path):
    return validate(json.loads(Path(path).read_text(), object_pairs_hook=sources.unique_object))


def check_inputs(root, bundle, frozen=True):
    validate(bundle)
    source_path = "tmp/sources.lock.json" if frozen else "tools/assembly/sources.lock.json"
    if sources.load(root / source_path) != bundle["sources"]:
        raise ValueError("dependency bundle does not match selected source revisions")
    if inputs_hash(root) != bundle["inputs_sha256"]:
        raise ValueError("maintained code changed; validate a new dependency candidate")
    if dependencies.go(root, "env", "GOVERSION", workspace=False).strip() != bundle["go_version"]:
        raise ValueError(f"dependency bundle requires {bundle['go_version']}")


def check_manifests(root, bundle):
    if manifests(root) != bundle["manifests"]:
        raise ValueError("canonical manifests changed during locked assembly")


def install(root, bundle):
    check_inputs(root, bundle)
    # Prevalidate every destination before creating any root manifest. Upstream
    # library manifests remain original source inputs, never silently overwritten.
    for name in MANIFESTS:
        path = safe_path(root, name)
        entry = bundle["manifests"][name]
        if name.startswith(LIB):
            if path.read_bytes().decode() != entry["content"]:
                raise ValueError(f"locked library manifest differs from original: {name}")
        elif path.exists():
            raise ValueError(f"refusing existing generated manifest: {name}")
    for name in MANIFESTS[:4]:
        content = bundle["manifests"][name]["content"]
        if content is not None:
            with (root / name).open("x") as output:
                output.write(content)


def version_key(version):
    match = SEMVER.fullmatch(version)
    if not match:
        raise ValueError(f"unsupported module version: {version}")
    major, minor, patch, prerelease = match.groups()
    identifiers = tuple((0, int(item)) if item.isdigit() else (1, item)
                        for item in prerelease.split(".")) if prerelease else ()
    return (int(major), int(minor), int(patch), prerelease is None, identifiers)


def seed(root, kubernetes):
    """Explicit update only: merge Go-parsed requirements, including test inputs."""
    if not re.fullmatch(r"1\.[0-9]+\.[0-9]+", kubernetes):
        raise ValueError("update requires an explicit Kubernetes release, e.g. 1.36.3")
    target = dependencies.release("k8s.io/kubernetes", "v" + kubernetes)
    documents = dependencies.source_documents(root)
    requirements = dependencies.validate_sources(documents)
    for label, path, version, value in requirements:
        if value > target or (path in dependencies.CORE and value[0] != target[0]):
            raise ValueError(f"{label}: {path} {version} cannot target Kubernetes {kubernetes}")
    merged, replacements, family = {}, {}, set()
    folded = {doc["Module"]["Path"] for label, doc in documents.items()
              if not label.startswith("csi-lib-utils@")}
    go_versions = []
    for label, document in documents.items():
        go_versions.append(tuple(map(int, document["Go"].split("."))))
        if document.get("Exclude") or document.get("Tool"):
            raise ValueError(f"{label}: unsupported exclude/tool directive; explicit adaptation required")
        for item in document.get("Require") or []:
            path, version = item["Path"], item["Version"]
            if path in folded:
                continue
            if dependencies.is_family(path):
                family.add(path)
                version = "v" + (kubernetes if path == "k8s.io/kubernetes" else "0." + kubernetes[2:])
            if path not in merged or version_key(version) > version_key(merged[path]):
                merged[path] = version
        for item in document.get("Replace") or []:
            old, new = item["Old"], item["New"]
            path = old["Path"]
            if path in folded and new["Path"] == "./client":
                continue
            if dependencies.is_family(path):
                if (new["Path"] != path or not new.get("Version") or
                        dependencies.release(path, new["Version"]) > target):
                    raise ValueError(f"{label}: cannot align replacement for {path}")
                family.add(path)
            else:
                if not new.get("Version"):
                    raise ValueError(f"{label}: unsupported local replacement for {path}")
                key = (path, old.get("Version", ""))
                if key in replacements and replacements[key] != new:
                    raise ValueError(f"conflicting source replacements for {path}")
                replacements[key] = new
    go_version = ".".join(map(str, max(go_versions)))
    lines = [f"module {ROOT_MODULE}", "", f"go {go_version}", "", "require ("]
    lines += [f"\t{path} {version}" for path, version in sorted(merged.items())]
    lines += [")", ""]
    for path in sorted(family):
        version = "v" + (kubernetes if path == "k8s.io/kubernetes" else "0." + kubernetes[2:])
        lines.append(f"replace {path} => {path} {version}")
    for (path, version), new in sorted(replacements.items()):
        lines.append(f"replace {path} {version} => {new['Path']} {new['Version']}")
    lines.append(f"replace {LIB_MODULE} => ./{LIB}")
    # Both files are fresh outputs. The library is a workspace module and keeps
    # its original requirements/checksums throughout update and locked builds.
    for name, content in (("go.mod", "\n".join(lines) + "\n"),
                          ("go.work", f"go {go_version}\n\nuse (\n\t.\n\t./{LIB}\n)\n")):
        with safe_path(root, name).open("x") as output:
            output.write(content)
    dependencies.go(root, "mod", "edit", "-fmt")
    dependencies.go(root, "work", "edit", "-fmt")


def check_layout(root):
    """Parse manifests without loading their graph or following workspace paths."""
    work = json.loads(dependencies.go(root, "work", "edit", "-json", str(root / "go.work"), workspace=False))
    uses = [item["DiskPath"] for item in work.get("Use") or []]
    if sorted(uses) != sorted([".", "./" + LIB]) or work.get("Replace"):
        raise ValueError("canonical workspace must contain only root and the locked library")
    for name, module_path in (("go.mod", ROOT_MODULE), (f"{LIB}/go.mod", LIB_MODULE)):
        document = json.loads(dependencies.go(root, "mod", "edit", "-json", str(root / name), workspace=False))
        if document["Module"]["Path"] != module_path:
            raise ValueError(f"unexpected canonical module identity: {name}")
        for item in document.get("Replace") or []:
            new = item["New"]
            if not new.get("Version") and not (name == "go.mod" and item["Old"]["Path"] == LIB_MODULE
                                              and new["Path"] == "./" + LIB):
                raise ValueError(f"unlocked local replacement in {name}")


def graph(root):
    check_layout(root)
    documents = dependencies.source_documents(root)
    modules = dependencies.resolved_modules(root)
    dependencies.validate_graph(modules, documents)
    return normalize_modules(modules)


def record(root):
    """Record pristine vendoring only after source and effective graph checks."""
    modules = graph(root)
    dependencies.validate_graph(dependencies.resolved_modules(root, True), dependencies.source_documents(root))
    data = {"modules": modules, "manifests": manifests(root), "vendor_sha256": vendor_hash(root)}
    with (root / "tmp/dependencies.pristine.json").open("x") as output:
        output.write(encoded(data).decode())


def capture(root):
    pristine = json.loads((root / "tmp/dependencies.pristine.json").read_text())
    if pristine["manifests"] != manifests(root) or pristine["modules"] != graph(root):
        raise ValueError("dependencies changed after pristine vendoring")
    bundle = {"schema_version": 1, "sources": sources.load(root / "tmp/sources.lock.json"),
              "inputs_sha256": inputs_hash(root),
              "go_version": dependencies.go(root, "env", "GOVERSION", workspace=False).strip(),
              **pristine, "adapted_vendor_sha256": vendor_hash(root)}
    bundle["payload_sha256"] = sha(encoded(bundle))
    validate(bundle)
    with (root / CANDIDATE).open("x") as output:
        output.write(encoded(bundle).decode())


def verify(root, bundle, phase):
    check_inputs(root, bundle)
    check_manifests(root, bundle)
    if phase == "graph":
        if graph(root) != bundle["modules"]:
            raise ValueError("resolved module graph differs from canonical lock")
    else:
        key = "vendor_sha256" if phase == "vendor" else "adapted_vendor_sha256"
        if vendor_hash(root) != bundle[key]:
            raise ValueError(f"{phase} dependency tree checksum mismatch")
    check_manifests(root, bundle)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--lock", type=Path)
    parser.add_argument("phase", choices=("preflight", "install", "seed", "graph", "vendor", "adapted", "record", "capture"))
    parser.add_argument("--kubernetes")
    args = parser.parse_args()
    root = args.root.resolve()
    if args.phase == "seed":
        seed(root, args.kubernetes or "")
    elif args.phase == "record":
        record(root)
    elif args.phase == "capture":
        capture(root)
    else:
        bundle = load(args.lock or root / LOCK)
        if args.phase == "preflight":
            check_inputs(root, bundle, frozen=False)
        elif args.phase == "install":
            install(root, bundle)
        else:
            verify(root, bundle, args.phase)
    print(f"Canonical dependencies: {args.phase} passed")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError) as error:
        raise SystemExit(f"Canonical dependencies failed: {error}") from error
