/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const provisionerLibrary = "vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v13/controller"

const libraryElection = `if ctrl.leaderElection {
 rl, err := resourcelock.New(resourcelock.LeasesResourceLock,
 ctrl.leaderElectionNamespace, strings.Replace(ctrl.provisionerName, "/", "-", -1),
 ctrl.client.CoreV1(), ctrl.client.CoordinationV1(),
 resourcelock.ResourceLockConfig{Identity: ctrl.id, EventRecorder: ctrl.eventRecorder})
 if err != nil { logger.Error(err, "Error creating lock"); klog.FlushAndExit(klog.ExitFlushTimeout, 1) }
 leaderelection.RunOrDie(ctx, leaderelection.LeaderElectionConfig{
 Lock: rl, LeaseDuration: ctrl.leaseDuration, RenewDeadline: ctrl.renewDeadline, RetryPeriod: ctrl.retryPeriod,
 Callbacks: leaderelection.LeaderCallbacks{
 OnStartedLeading: run,
 OnStoppedLeading: func() { logger.Error(nil, "Leaderelection lost"); klog.FlushAndExit(klog.ExitFlushTimeout, 1) },
 },
 })
 panic("unreachable")
} else { run(ctx) }`

const libraryMetrics = `if ctrl.metricsPort > 0 {
 prometheus.MustRegister([]prometheus.Collector{
 ctrl.metrics.PersistentVolumeClaimProvisionTotal, ctrl.metrics.PersistentVolumeClaimProvisionFailedTotal,
 ctrl.metrics.PersistentVolumeClaimProvisionDurationSeconds, ctrl.metrics.PersistentVolumeDeleteTotal,
 ctrl.metrics.PersistentVolumeDeleteFailedTotal, ctrl.metrics.PersistentVolumeDeleteDurationSeconds,
 }...)
 http.Handle(ctrl.metricsPath, promhttp.Handler())
 address := net.JoinHostPort(ctrl.metricsAddress, strconv.FormatInt(int64(ctrl.metricsPort), 10))
 logger.Info("Starting metrics server", "address", address)
 go wait.Forever(func() {
 err := http.ListenAndServe(address, nil)
 if err != nil { logger.Error(err, "Failed to listen metrics server", "address", address) }
 }, 5*time.Second)
}`

// methodSource copies only selected receiver methods and imports. Original
// library files remain untouched; standalone commands never call these siblings.
func methodSource(source []byte, receiver string, names ...string) ([]byte, error) {
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "library.go", source, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	a := &adapter{source: source, set: set}
	wanted := map[string]bool{}
	for _, name := range names {
		wanted[name] = true
	}
	var out strings.Builder
	out.WriteString("// Code generated by tools/cmd/lifecycle-adapter; DO NOT EDIT.\npackage " + file.Name.Name + "\n")
	out.WriteString("import (\"sync\"; \"fmt\")\n")
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			out.WriteString(a.text(gen) + "\n")
		}
		if fn, ok := decl.(*ast.FuncDecl); ok && wanted[fn.Name.Name] &&
			((receiver == "" && fn.Recv == nil) || (fn.Recv != nil && len(fn.Recv.List) == 1 && tokens(a.text(fn.Recv.List[0].Type)) == tokens("*"+receiver))) {
			out.WriteString(a.text(fn) + "\n")
			delete(wanted, fn.Name.Name)
		}
	}
	if len(wanted) != 0 {
		return nil, fmt.Errorf("missing %s methods: %v", receiver, wanted)
	}
	return []byte(out.String()), nil
}

func cloneProvisionerLibrary(source []byte) ([]byte, error) {
	source, err := methodSource(source, "ProvisionController", "Run")
	if err != nil {
		return nil, err
	}
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "run.go", source, 0)
	if err != nil {
		return nil, err
	}
	a := &adapter{source: source, set: set}
	var run *ast.FuncDecl
	for _, decl := range file.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok {
			run = fn
		}
	}
	if len(run.Body.List) < 2 {
		return nil, fmt.Errorf("incomplete library Run")
	}
	if run.Type.Results != nil || tokens(a.text(run.Type.Params)) != tokens("(ctx context.Context)") {
		return nil, fmt.Errorf("unexpected library Run signature")
	}
	var metrics, election int
	ast.Inspect(run.Body, func(n ast.Node) bool {
		if branch, ok := n.(*ast.IfStmt); ok {
			switch tokens(a.text(branch.Cond)) {
			case tokens("ctrl.metricsPort > 0"):
				if tokens(a.text(branch)) != tokens(libraryMetrics) {
					err = fmt.Errorf("library metrics shape changed")
					return false
				}
				a.replace(branch, "")
				metrics++
				return false
			case tokens("ctrl.leaderElection"):
				if tokens(a.text(branch)) != tokens(libraryElection) {
					err = fmt.Errorf("library election shape changed")
					return false
				}
				a.replace(branch, "run(ctx)\nreturn nil")
				election++
				return false
			}
		}
		return true
	})
	if err != nil {
		return nil, err
	}
	if metrics != 1 || election != 1 {
		return nil, fmt.Errorf("missing library lifecycle branch")
	}
	last := run.Body.List[len(run.Body.List)-2]
	if tokens(a.text(last)) != tokens("logger := klog.FromContext(ctx)") {
		return nil, fmt.Errorf("unexpected library election preamble")
	}
	a.replace(last, "")
	a.replace(run.Name, "RunAIO")
	a.insert(run.Type.Params.End(), " error")
	a.insert(run.Body.Lbrace+1, `
 if ctrl.leaderElection || ctrl.metricsPort != 0 { return fmt.Errorf("AIO owns provisioner election and HTTP services") }
 store, ok := ctrl.volumeStore.(*queueStore)
 if !ok { return fmt.Errorf("unsupported AIO volume store %T", ctrl.volumeStore) }
 ctx, cancel := context.WithCancel(ctx)
 ctrl.volumeStore = &aioQueueStore{queueStore: store, ctx: ctx}
 var wg sync.WaitGroup
 ctrl.ControllerWaitGroup(&wg)
 defer wg.Wait()
 defer cancel()
`)
	transformed, err := a.apply()
	if err != nil {
		return nil, err
	}
	return joinMethodGoroutines(transformed, "RunAIO", "wg")
}

// joinLaunch only moves evaluation of known stable controller/context values.
// Unknown receivers, channel receives, indexing, or calls fail generation rather
// than changing when an upstream expression is evaluated by a go statement.
func (a *adapter) joinLaunch(launch *ast.GoStmt, group string) error {
	var stable func(ast.Expr) bool
	stable = func(expr ast.Expr) bool {
		switch expr := expr.(type) {
		case *ast.Ident, *ast.BasicLit:
			return true
		case *ast.SelectorExpr:
			return stable(expr.X)
		case *ast.ParenExpr:
			return stable(expr.X)
		case *ast.BinaryExpr:
			return stable(expr.X) && stable(expr.Y)
		case *ast.CallExpr:
			return tokens(a.text(expr)) == tokens("ctx.Done()")
		case *ast.FuncLit:
			valid := true
			ast.Inspect(expr.Body, func(n ast.Node) bool {
				if _, ok := n.(*ast.GoStmt); ok {
					valid = false
				}
				return valid
			})
			return valid
		default:
			return false
		}
	}
	if !stable(launch.Call.Fun) {
		return fmt.Errorf("unrecognized goroutine function: %s", a.text(launch.Call))
	}
	for _, arg := range launch.Call.Args {
		if !stable(arg) {
			return fmt.Errorf("goroutine has evaluated arguments: %s", a.text(launch.Call))
		}
	}
	if fn, ok := launch.Call.Fun.(*ast.FuncLit); ok && len(launch.Call.Args) == 0 {
		a.replace(launch, group+".Go("+a.text(fn)+")")
	} else {
		a.replace(launch, group+".Go(func() { "+a.text(launch.Call)+" })")
	}
	return nil
}

func joinMethodGoroutines(source []byte, method, group string) ([]byte, error) {
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "joined.go", source, 0)
	if err != nil {
		return nil, err
	}
	a := &adapter{source: source, set: set}
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Name.Name != method {
			continue
		}
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			launch, ok := n.(*ast.GoStmt)
			if !ok {
				return true
			}
			if joinErr := a.joinLaunch(launch, group); joinErr != nil {
				err = joinErr
			}
			return false
		})
	}
	if err != nil {
		return nil, err
	}
	transformed, err := a.apply()
	if err != nil {
		return nil, err
	}
	return cleanImports(transformed)
}

func cloneQueueStore(source []byte) ([]byte, error) {
	source, err := methodSource(source, "queueStore", "Run", "StoreVolume", "saveVolumeWorker", "processNextWorkItem", "doSaveVolume")
	if err != nil {
		return nil, err
	}
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "store.go", source, 0)
	if err != nil {
		return nil, err
	}
	a := &adapter{source: source, set: set}
	background := 0
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		a.replace(fn.Recv.List[0].Type, "*aioQueueStore")
		if fn.Name.Name == "Run" {
			a.insert(fn.Body.Lbrace+1, "\nvar wg sync.WaitGroup\ndefer wg.Wait()\n")
		}
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			if call, ok := n.(*ast.CallExpr); ok && callName(call.Fun) == "context.Background" {
				if fn.Name.Name != "doSaveVolume" || len(call.Args) != 0 {
					err = fmt.Errorf("unexpected detached volume store call")
					return false
				}
				a.replace(call, "q.ctx")
				background++
			}
			return true
		})
	}
	if err != nil {
		return nil, err
	}
	if background != 1 {
		return nil, fmt.Errorf("unexpected volume store context shape")
	}
	out, err := a.apply()
	if err != nil {
		return nil, err
	}
	out = append(out, []byte("\ntype aioQueueStore struct { *queueStore; ctx context.Context }\n")...)
	return joinMethodGoroutines(out, "Run", "wg")
}

func cloneProvisionerConstructor(source []byte) ([]byte, error) {
	source, err := methodSource(source, "", "NewProvisionController")
	if err != nil {
		return nil, err
	}
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "constructor.go", source, 0)
	if err != nil {
		return nil, err
	}
	a := &adapter{source: source, set: set}
	a.insert(file.Name.End(), "\nimport k8sruntime \"k8s.io/apimachinery/pkg/runtime\"\n")
	var exits, registration, recorder, returns, broadcasters int
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		a.replace(fn.Name, "NewProvisionControllerAIO")
		if tokens(a.text(fn.Type.Results)) != tokens("*ProvisionController") {
			return nil, fmt.Errorf("unexpected constructor result")
		}
		a.replace(fn.Type.Results, "(*ProvisionController, func(), error)")
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			if block, ok := n.(*ast.BlockStmt); ok {
				for i, stmt := range block.List {
					call := expressionCall(stmt)
					if call == nil || !terminal(call) {
						continue
					}
					if i == 0 || tokens(a.text(call)) != tokens("klog.FlushAndExit(klog.ExitFlushTimeout, 1)") {
						err = fmt.Errorf("unknown constructor exit")
						return false
					}
					log := expressionCall(block.List[i-1])
					if log == nil || callName(log.Fun) != "logger.Error" || len(log.Args) < 2 || a.text(log.Args[0]) != "err" {
						err = fmt.Errorf("unknown constructor diagnostic")
						return false
					}
					a.replace(stmt, "return nil, nil, fmt.Errorf(\"%s: %w\", "+a.text(log.Args[1])+", err)")
					exits++
				}
			}
			if call, ok := n.(*ast.CallExpr); ok {
				switch callName(call.Fun) {
				case "v1.AddToScheme":
					if tokens(a.text(call)) != tokens("v1.AddToScheme(scheme.Scheme)") {
						err = fmt.Errorf("unknown constructor scheme registration")
						return false
					}
					a.replace(call, "eventScheme := k8sruntime.NewScheme()\nif err := v1.AddToScheme(eventScheme); err != nil { return nil, nil, err }")
					registration++
				case "broadcaster.NewRecorder":
					if len(call.Args) != 2 || a.text(call.Args[0]) != "scheme.Scheme" {
						err = fmt.Errorf("unknown constructor recorder")
						return false
					}
					a.replace(call.Args[0], "eventScheme")
					recorder++
				}
			}
			if assign, ok := n.(*ast.AssignStmt); ok && tokens(a.text(assign)) == tokens("broadcaster := record.NewBroadcaster(record.WithContext(ctx))") {
				a.insert(assign.End(), "\ncomplete := false\ndefer func() { if !complete { broadcaster.Shutdown() } }()\n")
				broadcasters++
			}
			if ret, ok := n.(*ast.ReturnStmt); ok && tokens(a.text(ret)) == tokens("return controller") {
				a.replace(ret, "complete = true\nreturn controller, broadcaster.Shutdown, nil")
				returns++
			}
			return true
		})
	}
	if err != nil {
		return nil, err
	}
	if exits != 3 || registration != 1 || recorder != 1 || returns != 1 || broadcasters != 1 {
		return nil, fmt.Errorf("constructor lifecycle shape changed")
	}
	out, err := a.apply()
	if err != nil {
		return nil, err
	}
	return cleanImports(out)
}

func generateDependencies(root string) error {
	outputs := map[string][]byte{}
	constructor, err := os.ReadFile(filepath.Join(root, provisionerLibrary, "controller.go"))
	if err != nil {
		return err
	}
	outputs["aio_constructor.go"], err = cloneProvisionerConstructor(constructor)
	if err != nil {
		return err
	}
	for name, adapt := range map[string]func([]byte) ([]byte, error){"controller.go": cloneProvisionerLibrary, "volume_store.go": cloneQueueStore} {
		source, err := os.ReadFile(filepath.Join(root, provisionerLibrary, name))
		if err != nil {
			return err
		}
		output, err := adapt(source)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		outputs["aio_"+name] = output
	}
	for name, output := range outputs {
		if err := os.WriteFile(filepath.Join(root, provisionerLibrary, name), output, 0644); err != nil {
			return err
		}
	}
	return nil
}
