/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

var workerSources = []string{
	"pkg/attacher/pkg/controller/controller.go",
	"pkg/provisioner/pkg/capacity/capacity.go",
	"pkg/provisioner/pkg/controller/clone_controller.go",
	"pkg/provisioner/pkg/controller/snapshot_finalizer_controller.go",
	"pkg/resizer/pkg/controller/controller.go",
	"pkg/resizer/pkg/modifycontroller/controller.go",
	"pkg/snapshotter/pkg/sidecar-controller/snapshot_controller_base.go",
}

// cloneWorker leaves the original Run method byte-for-byte unchanged. Its AIO
// sibling always selects the upstream tracked-worker path, independently of the
// release-on-exit policy, and joins auxiliary goroutines such as capacity polls.
func cloneWorker(source []byte) ([]byte, error) {
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "worker.go", source, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var run *ast.FuncDecl
	for _, decl := range file.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Recv != nil && fn.Name.Name == "Run" {
			if run != nil {
				return nil, fmt.Errorf("ambiguous worker Run methods")
			}
			run = fn
		}
	}
	if run == nil {
		return nil, fmt.Errorf("missing worker Run method")
	}
	a := &adapter{source: source, set: set}
	tracked := false
	for _, param := range run.Type.Params.List {
		if len(param.Names) == 1 && param.Names[0].Name == "wg" && tokens(a.text(param.Type)) == tokens("*sync.WaitGroup") {
			tracked = true
		}
	}
	if !tracked {
		return nil, fmt.Errorf("Run has no recognized worker wait group")
	}
	var gate *ast.IfStmt
	ast.Inspect(run.Body, func(n ast.Node) bool {
		branch, ok := n.(*ast.IfStmt)
		if ok && tokens(a.text(branch.Cond)) == tokens("utilfeature.DefaultFeatureGate.Enabled(features.ReleaseLeaderElectionOnExit)") {
			if gate != nil {
				err = fmt.Errorf("multiple worker tracking gates")
			}
			gate = branch
		}
		return true
	})
	if err != nil {
		return nil, err
	}
	if gate == nil || gate.Else == nil || gate.Init != nil {
		return nil, fmt.Errorf("unknown worker tracking shape")
	}
	// Retain the exact upstream tracked branch, then reparse before wrapping Go
	// statements. This prevents overlapping edits and preserves argument timing.
	a.replace(gate, a.text(gate.Body))
	a.replace(run.Name, "RunAIO")
	receiver := strings.TrimPrefix(a.text(run.Recv.List[0].Type), "*")
	if receiver == "csiSnapshotSideCarController" {
		a.insert(run.Body.Lbrace+1, "\nif ctrl.enableVolumeGroupSnapshots { defer ctrl.groupSnapshotContentQueue.ShutDown() }\n")
	}
	for _, stmt := range run.Body.List {
		if tokens(a.text(stmt)) == tokens("<-ctx.Done()") || tokens(a.text(stmt)) == tokens("<-stopCh") {
			a.insert(stmt.Pos(), fmt.Sprintf("klog.V(2).InfoS(\"AIO workers started\", \"worker\", %q)\n", receiver))
		}
	}
	transformed, err := a.apply()
	if err != nil {
		return nil, err
	}
	set = token.NewFileSet()
	file, err = parser.ParseFile(set, "tracked.go", transformed, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	a = &adapter{source: transformed, set: set}
	for _, decl := range file.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Name.Name == "RunAIO" {
			run = fn
		}
	}
	// Every launched goroutine, including auxiliary loops outside the gate, is
	// registered before it starts. Existing inner worker accounting is retained.
	ast.Inspect(run.Body, func(n ast.Node) bool {
		stmt, ok := n.(*ast.GoStmt)
		if !ok {
			return true
		}
		if joinErr := a.joinLaunch(stmt, "wg"); joinErr != nil {
			err = joinErr
		}
		return false
	})
	if err != nil {
		return nil, err
	}
	transformed, err = a.apply()
	if err != nil {
		return nil, err
	}
	set = token.NewFileSet()
	file, err = parser.ParseFile(set, "joined.go", transformed, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	a = &adapter{source: transformed, set: set}
	var out strings.Builder
	out.WriteString("// Code generated by tools/cmd/lifecycle-adapter; DO NOT EDIT.\npackage " + file.Name.Name + "\nimport \"k8s.io/klog/v2\"\n")
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			out.WriteString(a.text(gen) + "\n")
		}
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Name.Name == "RunAIO" {
			out.WriteString(a.text(fn) + "\n")
		}
	}
	return cleanImports([]byte(out.String()))
}

const topologyWorker = `func (nt *nodeTopology) RunWorker(ctx context.Context) {
 klog.Info("Started node topology worker")
 defer klog.Info("Shutting node topology worker")
 if !cache.WaitFor(ctx, "", nt.nodeInformer.Informer().HasSyncedChecker(), nt.csiNodeInformer.Informer().HasSyncedChecker()) { return }
 go func() { <-ctx.Done(); nt.queue.ShutDown() }()
 nt.queue.Add("")
 for nt.processNextWorkItem(ctx) {}
}`

func cloneTopology(source, fixed []byte) ([]byte, error) {
	source, err := methodSource(source, "nodeTopology", "RunWorker")
	if err != nil {
		return nil, err
	}
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, "topology.go", source, 0)
	if err != nil {
		return nil, err
	}
	a := &adapter{source: source, set: set}
	for _, decl := range file.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok {
			if tokens(a.text(fn)) != tokens(topologyWorker) {
				return nil, fmt.Errorf("unknown topology worker lifecycle")
			}
			a.replace(fn.Name, "RunWorkerAIO")
			a.insert(fn.Body.Lbrace+1, "\nctx, cancel := context.WithCancel(ctx)\nvar wg sync.WaitGroup\ndefer wg.Wait()\ndefer cancel()\n")
		}
	}
	fixedFile, err := parser.ParseFile(set, "fixed.go", fixed, 0)
	if err != nil {
		return nil, err
	}
	valid := false
	for _, decl := range fixedFile.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Name.Name == "RunWorker" && fn.Recv != nil {
			if len(fn.Recv.List) != 1 {
				return nil, fmt.Errorf("invalid fixed topology receiver")
			}
			star, ok := fn.Recv.List[0].Type.(*ast.StarExpr)
			valid = ok && callName(star.X) == "Mock" && len(fn.Body.List) == 0
		}
	}
	if !valid {
		return nil, fmt.Errorf("unknown fixed topology worker lifecycle")
	}
	out, err := a.apply()
	if err != nil {
		return nil, err
	}
	out = append(out, []byte(`
func RunWorkerAIO(ctx context.Context, informer Informer) error {
 switch worker := informer.(type) {
 case *nodeTopology: worker.RunWorkerAIO(ctx)
 case *Mock: <-ctx.Done()
 default: return fmt.Errorf("unsupported AIO topology informer %T", informer)
 }
 return nil
}
`)...)
	return joinMethodGoroutines(out, "RunWorkerAIO", "wg")
}

func generateWorkers(root string) error {
	// Validate all inputs before writing any generated sibling.
	outputs, err := snapshotOutputs(root)
	if err != nil {
		return err
	}
	for _, path := range workerSources {
		source, err := os.ReadFile(filepath.Join(root, path))
		if err != nil {
			return err
		}
		result, err := cloneWorker(source)
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		output := filepath.Join(root, filepath.Dir(path), "aio_"+filepath.Base(path))
		outputs[output] = result
	}
	topology := filepath.Join(root, "pkg/provisioner/pkg/capacity/topology")
	nodes, err := os.ReadFile(filepath.Join(topology, "nodes.go"))
	if err != nil {
		return err
	}
	fixed, err := os.ReadFile(filepath.Join(topology, "mock.go"))
	if err != nil {
		return err
	}
	joined, err := cloneTopology(nodes, fixed)
	if err != nil {
		return err
	}
	outputs[filepath.Join(topology, "aio_nodes.go")] = joined
	for path, result := range outputs {
		if err := os.WriteFile(path, result, 0644); err != nil {
			return err
		}
	}
	return nil
}
