---
name: Trivy vulnerability scanner
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Parse go version from .prow.sh
        run: |
          GO_VERSION=$(cat .prow.sh | grep "CSI_PROW_GO_VERSION_BUILD=" | head -1 | sed -E 's/.*CSI_PROW_GO_VERSION_BUILD="?([0-9.]+)"?.*/\1/')
          echo "Using go: $GO_VERSION"
          echo "$GO_VERSION" >> '.go-version'

      - name: Install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: .go-version

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Sync the assembly area from upstream kubernetes-csi repositories
        run: |
          export GOPATH=$(go env GOPATH)
          ./tools/scripts/cleanup.sh
          python3 -m venv .venv && source .venv/bin/activate
          ./tools/scripts/sync.sh

      - name: Build images from Dockerfile
        run: |
          make container-csi-sidecars
          make container-snapshot-controller
          make container-snapshot-conversion-webhook

      - name: Run Trivy vulnerability scanner on csi-sidecars image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'csi-sidecars:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Run Trivy vulnerability scanner on snapshot-controller image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'snapshot-controller:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Run Trivy vulnerability scanner on snapshot-conversion-webhook image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25  # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'snapshot-conversion-webhook:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
